#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
  #echo "You must be a root user, try sudo $0" 2>&1
  sudo $0
  exit 1
fi

/etc/init.d/eve-lock stop
su eve-lock -c "/home/eve-lock/lock/auth enroll -f /home/eve-lock/lock/prints/"
/etc/init.d/eve-lock start
